### ISSUE TITLE
Example of meteo netCDF subset for watershed. 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#132]
## Description

Create a notebook showing how to subset and aggregate climate variables for a watershed and feed the output to raven.

**Comment by richardarsenault** [comment]
Hi @Zeitsperre, I am wondering if you could give me an ETA for this, it is my main blocker for the rest of the notebooks / workflows. Thanks!

**Comment by huard** [comment]
This could in principle be done using the  `averager_WFS` process in flyingpigeon. We need to pass it the typename, the feature ids, the geoserver url and mosaic=True. Does our `hydrosheds-select` process return the feature ids ? I know it returns the basins id, but are they the same ?

**Comment by Zeitsperre** [comment]
Hey @richardarsenault, I can start on this and other tickets tomorrow. I'll be able to give you an estimate then.

**Comment by Zeitsperre** [comment]
Working on this today. Updates later.

**Comment by Zeitsperre** [comment]
@huard I can see in the feature that "id" is a top-level attribute (alongside geometry and properties) that is a copy of the "NEXT_SINK" and a potential bug in the GeoJSON output. Investigating this now.

The closest thing to a fid is the "id" property which uses the name of the table and the feature number (e.g. `"id": "USGS_HydroBASINS_lake_na_lev12.96929"`). This fid is only relevant if the source file is opened with GeoPandas, otherwise it makes more sense to use the "HYBAS_ID" to find specific features.
