### ISSUE TITLE
Create a notebook based GUI for region selection

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#174]
## Description

A notebook GUI where users can display polygons from a WFS layer, click on a region and get the associated polygon.

**Comment by davidcaron** [comment]
I was thinking we could benefit from creating a small utilities libraries for selecting entities, regions and general georeferenced user interaction inside a jupyter notebook. Something that could be reusable...

It's more of a medium term planning that would need more discussion, but I think we seem to be heading towards that. For simple inputs we can still get around with one-off helper functions.

**Comment by huard** [comment]
Sounds good. I suggest we embed those capabilities within an existing project to benefit, e.g. owslib. 
@tomLandry Worth discussing with Tom K ?

**Comment by davidcaron** [comment]
I think what I'm thinking about is a bit out of the scope of owslib, because owslib focuses on implementing ows standards (I could be wrong?) Kind of the same way that birdy is a 'more convenient' library over owslib for WPS processes.

I agree it would be nice to benefit an existing library, but I'm not sure which one...

**Comment by huard** [comment]
No, you're probably right. Let's keep looking.

**Comment by Zeitsperre** [comment]
I can recall coming across a python library maybe a year that had controlled terms for specific regions. I'll try looking through my old bookmarks to see if I can find it. Might be something that satisfies our needs that we can leverage for multiple projects. I'll update what I find here.

**Comment by Zeitsperre** [comment]
Found it: https://regionmask.readthedocs.io/en/stable/

There are a few pre-defined regions within the package (countries, SREX regions). This would be an interesting library to build upon to add a few more regions (Quebec, QC-CLIMEX, CORDEX, etc.). Again, this is probably a medium priority issue.

**Comment by huard** [comment]
@Zeitsperre Status ? I've got a meeting with Canarie next week and having this would be nice.

**Comment by Zeitsperre** [comment]
Haven't had time to work on this. Seeing that this is a priority, I'll put some hours into this today.

**Comment by Zeitsperre** [comment]
@huard Looking over the comments here, I can see that there's a lot of overlap with the needs of other services (finch in particular). I can also see where @davidcaron is coming from with the need for "a better owslib". 

As it stands, the way that RAVEN collects WFS layers is via some hard coded owslib functions in `gis.py`. This is due to the fact that we haven't figured ou a reliable and easy way to interface with our GeoServer instance. If we wanted to pull this out and into its own generic process, that would be fine for now, I imagine.

The approach I'm going to try is to see if I can use IpyLeaflet to pull data from the WFS and see if there's a way to extract coordinates from a mouse-click on a map object to setup a WFS `hydrobasins-select` process. I don't imagine it will be pretty but if you have any advice, feel free to pass it my way.

**Comment by huard** [comment]
I suppose one option would be to have a WFSLayer class in ipyleaflet. This is probably not trivial and may require some js coding. Step one would to be open an issue in ipyleaflet about this. 

As a first pass, can you reuse those raven gis functions inside a notebook and just display them inside the leaflet canvas ? 

Another option would be to download the layer as geojson and use something like this: https://ipyleaflet.readthedocs.io/en/latest/api_reference/geo_json.html#methods

**Comment by Zeitsperre** [comment]
@huard the basics are shown here. I'm still running into the issue with how old the RAVEN instance is on our PAVICS but both the API calls are in the notebook. I'm going to look into what functions can be turned into user-facing processes. I'll save my work to the #175 branch.

**Comment by huard** [comment]
I suggest to focus on the notebook for this branch and get it merged rapidly. Please open another issue for further backend work.

**Comment by Zeitsperre** [comment]
Okay. All I've done is add some type hinting to `utils.py`. I'll refrain on further backend work in that branch.
