### ISSUE TITLE
WPS for running streamflow hindcast ensembles using RAVEN

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#235]
Hindcasts are provided by Caspar. At the moment, a manuel request can be made to get Caspar data, which produces a globus collection that can then be transferred using the globus client. 

We could use climpred to organize the hindcasts.

**Comment by huard** [comment]
@julemai 

When we'll want to concatenate hindcasts starting on different days, we'll want to have two types of `time` variables: 
- the actual time of the forecast
- the *leadtime* from the `forecast_reference_time`

At the moment, the Caspar netcdf files only contain `time`, which I understand plays both roles. If I want to concatenate two forecasts from two different days, I'll need to differentiate those two times. 

Here is what ECMWF is proposing: https://confluence.ecmwf.int/display/COPSRV/Guide+to+NetCDF+encoding+for+C3S+providers

**Comment by julemai** [comment]
The time variable in the current NetCDF files is the _leadtime_. We do store all issues (actual time of forecast) in separate files (seen from filename and reference date in unit of time variable) to first avoid the necessity of two time variables and to avoid the merging of files on CaSPAr.

The files come in at each issue date/time and the products change. We don't want to carry all in one file because we would need to carry also different grids etc with us.

What the ECMWF recommends makes sense if we would have multiple forecasts in one file but we don't. We expect users to merge files themselves. The files you receive right now are good for running a model in forecast mode (along the _lead-times_ of the forecast). Raven wouldn't support multiple time axes either.

**Comment by huard** [comment]
Ok thanks !

**Comment by huard** [comment]
#321
