### ISSUE TITLE
WPS for querying ECCC weather forecasts through the GeoMET WPS service for the watershed of interest.

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#245]

**Comment by richardarsenault** [comment]
Self info:

WCS for netcdf example link: 
https://geo.weather.gc.ca/geomet?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=RDPA.24F_PR&SUBSETTINGCRS=EPSG:4326&SUBSET=x(-180,56.25000000000001)&SUBSET=y(12.211180191503997,85.70184378613162)&FORMAT=image/netcdf&TIME=2020-03-10T12:00:00Z

 - Replace COVERAGEID with the product (RDPS/GDPS)
 - Probably want to change the 12Z to 6Z for Canada, if available

**Comment by richardarsenault** [comment]
Variables description from: https://directory.spatineo.com/service/12371/

ETA_PR --> Precip accum [kg/(m^2)]
ETA_RN --> Rain accum [kg/(m^2)]
ETA_SN --> Snow accum [kg/(m^2)]
ETA_TT --> Air temperature [°C]

**Comment by richardarsenault** [comment]
@huard I have started the WPS process and test suite but there seems to be an intrinsic limitation in GeoMet:

"Note that queries with time ranges or multiple time values are not currently supported on GeoMet for both TIME or DIM_REFERENCE_TIME parameters. Only single time queries are supported."

What I gather from this is that we can only download one forecast step at a time... not super useful if we want to download 4 variables on say 40 time steps for each of 4 models (RDPS/GDPS/REPS/GEPS). Initial tests have shown that there is no time coordinate in the returned WCS-called netcdf...

see branch "wps_geomet" for details...

**Comment by richardarsenault** [comment]
@huard @tlogan2000 It might take a while before we can extract large amounts of data in single calls from GeoMET. Can we have a plan B where we download the ECCC forecasts from the datamart every day and store it temporarily on THREDDS (or elsewhere) for the past, say, 3-4 days? The data on Datamart is accessible for full forecasts (all lead-times at once) so that would make things much simpler.

I don't know how complicated it would be to setup an auto-download process for the required files, but if it's possible it's probably the next best thing. Or else we'll have to resort to submitting like 640 GeoMET requests each time we want to do a forecast.

Any comments or suggestions welcome!

**Comment by tlogan2000** [comment]
Creating the proper download script is probably the jump-off point and the most critical.  Automating it to run every day should be fairly simply for Long I would think....

**Comment by tlvu** [comment]
> Creating the proper download script is probably the jump-off point and the most critical. Automating it to run every day should be fairly simply for Long I would think....

Yes.  Someone write the script, I can hook it up to our cronjobs on PAVICS easily.

**Comment by richardarsenault** [comment]
It would seem ECCC has an "Advanced Message Queuing Protocol" (AMQP) that allows automatically receiving the desired forecast data as soon as it is available: https://eccc-msc.github.io/open-data/msc-datamart/amqp_fr/

It runs in python so should be relatively easy to implement I would think? I know some hydropower utilities use this and usually works well.

Now just trying to find the good variables on the datamart, which seems to be proving more difficult than anticipated...

**Comment by huard** [comment]
Closed with #321
