### ISSUE TITLE
Create a raven-testdata repo

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/raven#318]
@tlvu 

@huard would like for us to create a `raven-testdata` repository to support Raven (and PyRaven, I imagine). He mentioned that you had already started some work on this. My questions to you are :
 - Would you want something that very closely resembled `xclim-testdata` ?
   - Would this repo include a script for generating an MD5 sum for files ?
 - What types of files will likely be in this repo ?
   - Would they be very large ? Do we need `git-lfs` ?
 - Any other pertinent needs ?

**Comment by tlvu** [comment]
@Zeitsperre @huard  I though the conclusion was to leave the raven test data where they currently are (in the Raven repo), as in this comment https://github.com/Ouranosinc/xclim-testdata/pull/1#issuecomment-704526067, reasoning https://github.com/Ouranosinc/xclim-testdata/pull/1#issuecomment-704281014.

I did not have time to finish https://github.com/Ouranosinc/raven/issues/185 and I believe what's left to do are:

* Create a function `raven.tutorial.get_file` that knows how to handle different file types. In the case of netCDF either returns an http or dap link from thredds, and for other files return the rawgithub link (see https://github.com/Ouranosinc/raven/issues/185#issuecomment-709412566)

* Given this `raven.tutorial.get_file` function is part of the same Raven repo as the testdata, it should detect that the testdata are local (the case of a dev checkout and running CI) and return the local file instead of always fetching it over the internet.  Further reasoning https://github.com/Ouranosinc/raven/issues/185#issuecomment-709436073.

**Comment by Zeitsperre** [comment]
https://github.com/Ouranosinc/raven-testdata
