### ISSUE TITLE
Notebook "Running HMETS with CANOPEX" fails due to Gateway timeout

### ISSUE THREAD

**Issue by richardarsenault** [Ouranosinc/raven#362]
The notebook runs fine at first, then at cell number 5 it fails with a gateway timeout error, even if the number of calibrations is set to a very small number (50).

**Comment by tlvu** [comment]
Same as https://github.com/Ouranosinc/raven/issues/357#issuecomment-772188863, if use Raven from my dev server, no timeout error !

**Comment by huard** [comment]
It may be a different issue, but long running processes should be run in async mode. I would argue however against using async processes in notebooks. 
1. Notebooks should run fast, otherwise people going through them as training might lose patience
2. They are used for testing, so long running notebooks slow feedback
3. The test suite does not wait for async processes, so the test just fails.

**Comment by tlvu** [comment]
> It may be a different issue, but long running processes should be run in async mode. I would argue however against using async processes in notebooks.

@huard Like I've found out in my PR to increase the proxy timeout, the reason this notebook is taking a long time is because Raven takes too much time to respond to the request.

Using Raven on my crappy dev VM, this entire notebook finish in less than 3 minutes.

**Comment by tlvu** [comment]
> Using Raven on my crappy dev VM, this entire notebook finish in less than 3 minutes.

From a tutorial perspective, I think if a notebook takes more than 1 minute, it's too long for the user.  Especially if the user intend to try more than 1 notebooks.
