### ISSUE TITLE
WPS client generator

### ISSUE THREAD

**Issue by tomLandry** [Ouranosinc/raven#40]
From Statement of Work. Script automatically generates client library from WPS description, Code to automatically generate client libraries (eg python) from WPS description.

**Comment by tomLandry** [comment]
@huard Would like to start contributions (tests, experiments) from my colleague David on this component. You would be in a good place to briefly describe the entry points to this.

**Comment by tomLandry** [comment]
Trying to catch the bird while it's flying away :-) https://github.com/bird-house/birdy/pull/55

**Comment by huard** [comment]
The code is in https://github.com/bird-house/birdy/blob/master/birdy/native.py
The usage docs are here: https://birdy.readthedocs.io/en/latest/usage.html#module-birdy.native
There are a few tests already in tests/test_native.py 

What is missing 
- tests that exercise various types of inputs and outputs, either through references or actual data;
- tests for authentication
- compliance checks with the WPS standard. I've only tested against pywps, so I'm expecting things to break if we use another WPS server. Just changing a pywps version broke stuff...

Note that it's possible that some upstream fixes to pywps need to be made for some corner cases.

**Comment by tomLandry** [comment]
Thank you, my good sir. Because that's current work, I suggest we start with "tests for authentication". Stuff will break anyway. For various types of IO, we'll give it a go soon.

**Comment by huard** [comment]
Ok, fais-moi signe si tu veux qu'on en parle.

**Comment by davidcaron** [comment]
@huard 
You can take a look at this branch: https://github.com/davidcaron/birdy/tree/refactor

I modified the module quite a bit so here is a summary:
- use boltons.funcutils.FunctionBuilder to create functions dynamically instead of eval/exec statements
- the import_wps function returns a class instead of a module... I felt that simplified the execution of processes. And import_wps  is equivalent to the BirdyClient class. Any method that is not private on the class is a WPS process.
- expose username, password, headers, verify and cert so that they are passed to owslib for authentication
- Raise appropriate error when unauthorized
- convert outputs (int, float, bool, datetime) to python types instead of keeping the strings returned from owslib
- It seems that all of the data types work, except the bounding box type. I've seen in a comment that owslib doesn't support it, but I'm not sure if that's actually true...
- netCDF tries to open the link as OpenDAP, and if that doesn't work the file is downloaded
- probably some more things I'm forgetting...

Try it out and let me know, I wanted to check with you before submitting a PR.

**Comment by huard** [comment]
Excellent. I created a PR and asked a few questions. The build seems to fail due to flake8. 

Does it work with pywps master ? I've tried it and I/m getting a few failures related dataTypes. There have been changes in pywps last summer, They changed their output to templates and now stick more closely to the OGC standard. There is a PR about this https://github.com/geopython/pywps/pull/415

Ideally, birdy would manage to be compatible with the latest release and the current master.
