### ISSUE TITLE
WPS interface for the HBV-EC emulator (2)

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#9]

**Comment by julemai** [comment]
@richardarsenault 

HBV-EC is one of the standard emulations in RAVEN. So no problem at all. Do you have a benchmark setup in, e.g., Matlab? I'd only need that to:
* get parameter ranges,
* a default parameter set, and
* parameters you want to calibrate

Then I need a quick chat with James because he has to show me where I find all these in the *.rvp file and that's it.

**Comment by richardarsenault** [comment]
@julemai 
We do not have HBV-EC in Matlab, this is a new model for me. I've used a watered-down version before (Amir AghaKouchak's academic version) but I unfortunately cannot find it anymore (it was experimental). Does RAVEN have "proposed" or "default" boundaries for the models?

**Comment by julemai** [comment]
@richardarsenault 
Ok. No problem. I only wanted to be sure that you don't have a code I could compare to.
I will find out what the HBV-EC specific model parameters are and will look for ranges. Might take a while. I can work on that a bit next week.

**Comment by julemai** [comment]
@richardarsenault @huard 

I'm done with the HBV-EC setup. since I didn't have a reference HBV implementation you want to use, I went through all the hard-coded values in the `*.rv*` setup files with James. We identified 21 parameters where most of them are used in some versions of HBV. 

The Wiki is updated. Here are:
- The <a href="https://github.com/Ouranosinc/raven/wiki/raven-template-setups/raven-hbv-salmon.zip" download="raven-hbv-salmon.zip">Raven setup</a>
- The <a href="https://github.com/Ouranosinc/raven/wiki/raven-template-setups/raven-hbv-salmon.zip" download="ostrich-hbv-salmon.zip">Ostrich setup</a>

**Comment by huard** [comment]
@julemai Excellent ! Sorry for my slow response these days, I've been handed a short term assignment that takes all my time. Should be back in the game next week.

**Comment by julemai** [comment]
No problem. Now that I have figured out how this whole WPS thing is working. I would feel comfortable to add that for MOHYSE and HBV (if you would create a branch for me). I could do that after the generic_raven branch is merged back. :)

Have a great weekend!

**Comment by huard** [comment]
Yep, will start by merging your changes into master. You don't need me to create a branch though. Once I've merged the generic_raven branch, you can update your master and then create an hbv branch (`checkout -b hbv`), commit your changes then push the hbv branch to github (`push --set-upstream origin hbv`) and create a PR.

**Comment by julemai** [comment]
Ok. I will give it a try. I’ve met done that before.

**Comment by julemai** [comment]
Done.
