### ISSUE TITLE
Set generic_zonal_stat default raster to the raster stored on GeoServer

### ISSUE THREAD

**Issue by huard** [Ouranosinc/raven#98]
## Description

Users are not expected to have a DEM raster on their machine. They should be able to use the default one provided on our GeoServer. 

In other words, set the default `raster_url` to the correct GeoServer link on pavics.

**Comment by Zeitsperre** [comment]
Just for clarification, the coverage of this raster should comprise all of Quebec? Canada? North America? I'll continue with the EarthEnv DEM90 data set, I just need to know many tiles to collect and merge together before uploading.

**Comment by huard** [comment]
Let's start with North America.

**Comment by Zeitsperre** [comment]
@huard The DEM is merged and working on one test server (CRIM) and the Ouranos prod server. Since the file itself is around 24G, the DEM tiles needed to be precached (thanks to @davidcaron for the help with that). The layer loads fairly quickly on the frontend from what I can tell. 

You probably already know this but the best way to access the tile is through WCS 2.0.1 protocol. A request using a BBox might resemble the following:
```http://<server>:8080/geoserver/ows?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=public:EarthEnv_DEM90_NorthAmerica&subset=Long('.$minX.','.$maxX.')&subset=Lat('.$minY.','.$maxY.')```

Let me know if you have problems accessing the DEM. I haven't played around with WCS yet and could benefit from the practice.

**Comment by huard** [comment]
Excellent! Will try next week to integrate into the process.

**Comment by Zeitsperre** [comment]
Visibility is better using the Roads base map. Not sure where I can increase the opacity but hey it works: 
![Screenshot_2019-04-09_15-29-36](https://user-images.githubusercontent.com/10819524/55830344-b0fb2780-5ade-11e9-8a9b-28f290809b9d.png)
